version: 0.2

phases: 
    install: 
      runtime-versions:
        nodejs: 10
      commands:
        - npm install -g serverless@1.60.4
    pre_build:
      commands:
        - npm install
    build:
      commands:
        - npm run test   
artifacts:
  files:
  - ./**/*